### ISSUE TITLE
Feature Request - Blueprint Upgrader

### ISSUE THREAD

**Issue by TheZombiee** [Nexela/PickerExtended#15]
The current function works wonderfully but it's clunky to select one item at a time.  Rather than the two boxes to select items, it would be nice to create multiple rule sets similar to upgrade planner and select which you want to use when grabbing a blueprint.

EG - I create a rule set ahead of time to upgrade yellow belts, undergrounds and splitters to red.  I select my lane balancer blueprint and your UI element pops up, I select appropriate rule set and click upgrade.  Poof - better blueprint.

Integration with upgrade planner would be ideal but probably much harder to do than I comprehend.  Regardless, I love your mods and appreciate the work you do on them.

**Comment by Nexela** [comment]
Not sure how this fits into the theme of picker,  It might be better suited for upgrade planner.

**Comment by TheZombiee** [comment]
Agreed, but it seemed a fitting extension to picker's blueprint flipper/upgrade toolbar once I starting using it.  With blueprints persisting across saves now, it's probably not something you'd actually use often enough to justify creating in the first place.

**Comment by Nexela** [comment]
I will pester Klonan and get it added to upgrade planner :)

**Comment by Nexela** [comment]
Pestering finished, Latest version of upgrade planner now supports upgrading blueprints.
