### ISSUE TITLE
Add default values to all settings

### ISSUE THREAD

**Issue by Choumiko** [Nexela/PickerExtended#2]
Having all settings a tooltip with the default Factorio values would be nice.

About the corpse removal time: Does this affect only tree stumps and biter corpses or also the new feature that the player leaves behind a corpse which can be looted? (My first thought was the later, but in the file there's stum be gone mentioned so i assume it's not the player?) Maybe add a info/hint in the tooltip.

**Comment by Nexela** [comment]
Agreed, I will expand upon these and also check player corpse
It affects all corpses that have the default corpse time of 15 minutes, which is most corpses.
