### ISSUE TITLE
Pickup Loot Distance & Pickup Item Distance tooltips swapped in startup mod settings

### ISSUE THREAD

**Issue by Syllus** [Nexela/PickerExtended#21]
When creating a new game, on the startup mod settings screen the tooltips for "Pickup Loot Distance" and "Pickup Item Distance" seem to be swapped -- they don't match the names.  Or maybe it's the names that are swapped; I'm not certain.

**Comment by Nexela** [comment]
Thanks! Fixed in the next version.   The Names were swapped
