### ISSUE TITLE
Game lag when really full really large chest sorted

### ISSUE THREAD

**Issue by TokMor** [Nexela/PickerExtended#22]
Game lags when a mostly full warehouse is opened. Recommend adding a setting for the max amount of things in a chest auto-sort will try to sort, if the chest contains more than that then the autosort function should not trigger.

**Comment by TokMor** [comment]
It appears to be based on the number of unique items in the container, opening a container full of the same thing has no issues

**Comment by Nexela** [comment]
Hmmm what if the warehouse is 50% one 50% another does it still lag?

**Comment by TokMor** [comment]
It does not appear to lag if it is full of 2 items

**Comment by Nexela** [comment]
Ok, I will set it to ........... 20 items as a testerification.  What I really need to do is re-write the sorting to be nexela approved :)
