### ISSUE TITLE
Feature Request: Quick Decon Planner

### ISSUE THREAD

**Issue by MSixteen16** [Nexela/PickerExtended#25]
Make picker so you can do something like with the small blueprint thing you already have except it gives you a decon planner with that entity filtered. So Control X on a belt gives a decon planner filtered for that belt. Maybe selecting a tree turns on "Just Trees" or somethig.

**Comment by Nexela** [comment]
With PickerBlueprinter  pressing delete on any item will mark it for deconstruction.   if you are holding a deconstruction planner pressing delete will add that entity to the white/black list
