### ISSUE TITLE
Request When you run out of an item

### ISSUE THREAD

**Issue by JohnyDL** [Nexela/PickerExtended#30]
You have this awesome feature where you can swap the conveyors with the brush belt in situ an extension of this might be when you run out of an item (any item) instead of just not being able to place anymore it swaps in a blueprint of that single item a picker click in the inventory might even allow you to make a blueprint for an item you don't have on hand and can't make without needing to switch to map view and go hunting to make your own.

**Comment by Nexela** [comment]
Hmmmm... I kind of like this idea, Shouldn't be too hard to implement either.

on_put_item if item.count == 1 then pdata.last_item = item
on_cursor_changed if not valid for read and pdata.last_item
make quick bp of last item

**Comment by JohnyDL** [comment]
I'm kind of surprised no-one had ever thought of this one before XD

**Comment by Nexela** [comment]
Will be in the next version!
