### ISSUE TITLE
0.15.13 - Orphan Checker error

### ISSUE THREAD

**Issue by andyeff** [Nexela/PickerExtended#31]
!! Nexela, disregard below post mostly! I have troubleshot some more, please see second post! :)

Hi Nexela, I started getting an error in my game today after running some underground belt over a stack inserter.
`/picker/belttools.lua:17: attempt to index field 'neighbours' (a nil value) `
`LuaEntity doesn't contain key 1. stack traceback: __PickerExtended__/picker/belttools.lua:17 in function<__PickerExtended__/picker/belttools.lua:12> [C]: in function 'pcall' __PickerExtended__/stdlib/event/event.lua: 78: in function <__PickerExtended__/stdlib/event/event.lua:71> `

The knock-on effect is that I now receive this error constantly whenever I mouse over belt or UG belt (but not pipes)
`/picker/orphans.lua:26: bad argument #1 to 'next' (table expected, got nil)`

Disabling the option 'Find Unconnected Undergrounds' suppresses most of these errors, but attempting to UG over a stack inserter still causes some errors to appear (as above)

Screenshot for reference: 
![9196e8cc-4d3c-48ca-a1ba-643fa4a7d5a1](https://cloud.githubusercontent.com/assets/3918580/26366086/a7da2774-3fe1-11e7-8763-a1b1b022c9b4.jpg)

I'm playing with the following mods enabled: 
![1401546a-789d-4c11-894c-688881189f4a](https://cloud.githubusercontent.com/assets/3918580/26366111/c1ebfab6-3fe1-11e7-85a0-219481194f04.png)

And using the following Picker settings:
![4f75051a-b561-4cee-a732-447f28185187](https://cloud.githubusercontent.com/assets/3918580/26366128/d288c91c-3fe1-11e7-87b3-3d5aead05f14.png)

![afb77efe-adcc-46fa-94d7-c1d0b614fe3c](https://cloud.githubusercontent.com/assets/3918580/26366130/d4486370-3fe1-11e7-920b-fb8e7c7de3c4.png)

**Comment by andyeff** [comment]
I created a new game, disabled the one new mod I've installed (warehousing), turned on cheat mode and placed underground belt.

Immediately received errors.

Therefore I think something in 0.15.13 (which installed before I played today) is possibly incompatible with the orphan checker code?

I'll see if I can roll back to 0.15.12 and try again.

**Comment by Nexela** [comment]
There will be a fix shortly :)
