### ISSUE TITLE
Moving Belt Sorters breaks 

### ISSUE THREAD

**Issue by Djzonk** [Nexela/PickerExtended#32]
If you move a belt sorter it will glitch out creating a broken version of the belt sorter in the new position and leaving another version in its old position. 
It also makes it so you can not place any other objects in the broken tiles 
![broken tiles](https://cloud.githubusercontent.com/assets/6174406/26368215/8e8319aa-3fb6-11e7-8f29-5deeb198befc.png)
as you can see in the image the two tiles left of the belt inserter have the blue plus in them, those are the broken tiles that i can't place anything in.
also if there is any console command that may fix those tiles so i can use them again it would be apreaciated
[Belt Sorter](https://mods.factorio.com/mods/judos/beltSorter)

**Comment by Nexela** [comment]
For the moving issue, belt sorter would have to register to pickers dolly events api.

Does mining the belt sorter remove the left behind entities?

**Comment by Nexela** [comment]
```
/c local p = game.player.position for _, ent in pairs(game.player.surface.find_entities_filtered{name="belt-sorter-lamp", area={{p.x-20, p.y-20}, {p.x+20, p.y+20}}}) do ent.destroy() end
```

**Comment by Djzonk** [comment]
you cant mine the entity that is left behind but if you mine the one in the new position the one left behind disappears but what i'm assuming is a lamp entity (not very versed in factorio modding gathered that from the command you gave me) is still there. 
also the command worked perfectly thank you.
