### ISSUE TITLE
Server crash when blueprint picking a rail

### ISSUE THREAD

**Issue by cpw** [Nexela/PickerExtended#33]
Got this crash when I picked a rail on my multiplayer server. Had to restart the server.

11408.205 Error MainLoop.cpp:850: Exception at tick 37262969: Error while running event PickerExtended::picker-make-ghost (ID 77)
Unknown item name: straight-rail
stack traceback:
        __PickerExtended__/picker/blueprinter.lua:76: in function <__PickerExtended__/picker/blueprinter.lua:50>
11408.205 Error ServerMultiplayerManager.cpp:94: MultiplayerManager failed: "Error while running event PickerExtended::picker-make-ghost (ID 77)
Unknown item name: straight-rail
stack traceback:
        __PickerExtended__/picker/blueprinter.lua:76: in function <__PickerExtended__/picker/blueprinter.lua:50>"
11408.205 Info ServerMultiplayerManager.cpp:670: mapTick(37262969) changing state from(InGame) to(Failed)

**Comment by Nexela** [comment]
Totally missed this one, will have it fixed this weekend!

**Comment by Nexela** [comment]
Factorio bug, will be fixed in .15.16
https://forums.factorio.com/viewtopic.php?f=30&t=48610
