### ISSUE TITLE
Rotating combinators no longer works.

### ISSUE THREAD

**Issue by 5trick3n** [Nexela/PickerExtended#37]
Rotating combinators with CTRL+SHIFT+R no longer works for me. I haven't changed any settings, though I think it started happening after one of the recent updates.

**Comment by Nexela** [comment]
Check they keybinds. Sometimes the get reset Also the rotate keybind did get changed to the numpad.

**Comment by 5trick3n** [comment]
Yep. I saw DEL in the keybinds, but never even realized there was one on the numpad. Thanks! Love the mod btw. It's essential in all my play-throughs!
