### ISSUE TITLE
Option to show entity info when using screenshot tool

### ISSUE THREAD

**Issue by asifbaig01** [Nexela/PickerExtended#40]
Fantastic mod. Excellent collection of some very useful QOL improvements. 

One small request. While the screenshot tool is probably the easiest to use from all the alternatives out there, it desperately needs the option to show entity info (that we get by pressing Alt in the game). Otherwise all assemblers look the same and you can't really tell from the screen what structure is making what.

**Comment by Nexela** [comment]
Thanks!
Shift dragging will take a screenshot with entity info
