### ISSUE TITLE
Inventory explosion after upgrading Picker from 2.6.1 to 2.7.0+

### ISSUE THREAD

**Issue by Syllus** [Nexela/PickerExtended#42]
After updating Picker from 2.6.1 to 2.7.2, I loaded up my save game and clicked on an item in my inventory.  The result was an inventory explosion all over the ground.  After some testing, it seems that this problem was introduced with Picker 2.7.0.  (Swap in 2.6.1 and open save, the bug does not happen.  Swap in 2.7.0, bug happens.)

Theory:
I'm using Jazomeds Tweaks mod to multiply all stack sizes by 20.  Explosion seems to happen because stack size of some items reverts to vanilla.  I'm not sure why Picker 2.7.0 would cause this, but it does.  Items that seem to be affected, based upon what's currently in my inventory:

- stone blocks
- water fill
- concrete

Here's my save:
https://drive.google.com/open?id=0B5DkdO2J4W0ZY3ZFWnFYd2k0VmM
And my mods folder (all mods are active):
https://drive.google.com/open?id=0B5DkdO2J4W0ZNzlfaHZsZDFlaHc

Specific steps to reproduce:
1.  Load save (named "2017-05-11 0.15 few mods")
2.  Open inventory
3.  Click on an item in inventory (I know iron plates and single splitter both reproduce it for sure)

**Comment by Syllus** [comment]
I should probably also include my Factorio version: 0.15.18
The save was from Factorio 0.15.16

**Comment by Nexela** [comment]
Looks like I forgot a check.  Will have it fixed in the next release, until then you can manually set the tile stack size in options startup.

**Comment by Syllus** [comment]
Ah, that makes sense, thanks.  I actually saw that option in Picker when I was trying to diagnose the problem, but that was before I noticed that only 'tile' stacks were affected, so I never made the connection.
