### ISSUE TITLE
bug with LightedPolesPlus

### ISSUE THREAD

**Issue by camarril** [Nexela/PickerExtended#43]
This mod adds electric poles with integrated lights:
[https://mods.factorio.com/mods/Optera/LightedPolesPlus](url)

If you move a pole, the light does not move with it.
This leads to an invisible light, that you can not remove. 

If you move the pole back and then delete it, the light gets removed too.
If you move it and delete it at another position, the light stays forever. It starts blinking, if it has no power like a normal lamp.

Even if you can't solve this, I still love this mod. Keep up the great work :)

**Comment by Nexela** [comment]
Optera would need to add explicit support for picker dollies, I provide an API for it.

**Comment by Yousei9** [comment]
Done in [Lighted Electric Poles +](https://mods.factorio.com/mods/Optera/LightedPolesPlus) 0.1.3.
