### ISSUE TITLE
Rotating oblong combinator places entities off grid

### ISSUE THREAD

**Issue by Yousei9** [Nexela/PickerExtended#44]
1. rotate oblong combinator rotates constant combinators off grid
![2017-06-07-10-12-43-0957036](https://user-images.githubusercontent.com/8436934/26868711-3e723f3a-4b6a-11e7-82eb-54ed6c3addfb.jpg)

A check to make this shortcut work only on 2x1 combinators seems to be missing.

2. using rotate oblong combinator on a constant combinator after being used on an arithmetic or decider places both off grid
![2017-06-07-10-12-48-0239855](https://user-images.githubusercontent.com/8436934/26868722-42f00d30-4b6a-11e7-9de4-ce46abe59761.jpg)

Rotations should not remember last entity and simply try rotate what's under the cursor.

**Comment by Nexela** [comment]
Should be fixed in the next release
