### ISSUE TITLE
Make Hide planners option false by default

### ISSUE THREAD

**Issue by Choumiko** [Nexela/PickerExtended#45]
I got a bug report for Module Inserter that the selection tool is missing, which lead to quite the hunt :D
I quadruple checked my code, everything looked fine. Downgraded Factorio on Steam to 0.15.15, everything works. Upgrade to 15.16, all good, repeat up to 0.15.19, still works. The non steam version doesn't work. Smart me knows it has to be another mod, so in the end it was quite easy to find.

Storytelling aside, i think such recipe changing settings should be opt in and not opt out. For the hide planner option it's probably too late now, but for new settings it could be a good idea?

Don't know how many mods that add a selection tool, i posted the solution for Module Inserter and Upgrade planner (which also had a report about the missing item)

**Comment by Nexela** [comment]
You should have seen the first iteration! there wasn't even an option :)    I will make the change for the next release
