### ISSUE TITLE
Dolly-moving entities with fluid boxes

### ISSUE THREAD

**Issue by AlexanderPruss** [Nexela/PickerExtended#49]
Inspired by a few videos from Arumba - it would be great if moving entities also worked for entities that had fluid boxes. I'll try and get a PR for this up in the next few days - since these entities can't be teleported, I'm doing it like this:

1. Mine the entity
2. Attempt to create a new entity in the target position - failing that, return it to its old position
3. Remove the mined entity from the player's inventory

If there's a better way to do this, let me know. This is my first time working with the Factorio modding API.

**Comment by Nexela** [comment]
It's really not worth the effort.  If you do something like this I will look at it.

Don't forget you have to store and restore all the fluid boxes.
Handle it if it can't be mined.
Mining fluid boxes pushes fluid back along the lines so this has to be accounted for also by clearing the fluidboxes before mining them.

**Comment by Shirkit** [comment]
One can also enable to move assemblers type only with fluid boxes, by just losing the fluids. Most people would certainly not care about losing liquids in that way.

Or could do the Nelexa way.
