### ISSUE TITLE
Ore stack size overridden when Dectorio gravel enabled

### ISSUE THREAD

**Issue by dgw** [Nexela/PickerExtended#59]
Dectorio optionally allows placing ores (coal, copper, iron, and stone) as floor tiles that look like gravel. Picker overrides ore stack sizes when that option is enabled, because ores gain a `place_as_tile` property that makes Picker think they're just like any other tile. By default, ore stacks are doubled from vanilla's 50 to Picker's default tile stack size of 100. (See jpanther/Dectorio#44)

While this can be worked around by setting `picker-tile-stack` to 50, that means the function isn't usable for other, non-ore tile types.

The fixes that occur to me are:

1. Simple option: Add a toggle to disable Picker's tile stack changing function. (I noticed it's [not guarded](https://github.com/Nexela/PickerExtended/blob/c863580/prototypes/final-fixes/small-fixes.lua#L192) by a setting.) This is essentially like setting the tile stack size to something small, because Picker will not decrease the stack size of a tile type, only increase.
2. More complicated option: Skip overriding the four ores Dectorio touches, since they're not tiles unless that mod is present.
3. Most complicated idea: Skip any ores, including ores added by other mods (Angel's, etc.)—probably not worth the effort, to be honest.

**Comment by Nexela** [comment]
This option has been moved to picker tweaks mod for .16. Additionally setting the setting to a value of 0 will not change any stack sizes.
