### ISSUE TITLE
Fuel Generator Equipment error

### ISSUE THREAD

**Issue by Ranakastrasz** [Nexela/PickerExtended#60]
If you have burner-generator type equipment in module armor, you get an error message when you either open it or put something in. Or something related to that.

Presumably, because vanilla lacks this it was not tested.

![capture 1](https://user-images.githubusercontent.com/1939919/33790334-5d09ee1a-dc4d-11e7-9d4a-6ee6581c27a1.PNG)

Luckily this only shows the error, it doesn't seem to break anything. Presumably results in the thread being terminated.

**Comment by Nexela** [comment]
Do you have a mod I can drop in that will cause this behaviour?

**Comment by Ranakastrasz** [comment]
https://forums.factorio.com/viewtopic.php?f=93&t=14894

**Comment by Nexela** [comment]
I believe this is fixed in +3.0.0  for .16, Please re-open if it still persists
