### ISSUE TITLE
[0.16.1 / 3.0.0] R to rotate held items also rotates placed entities when Picker Extended is enabled.

### ISSUE THREAD

**Issue by dewiniaid** [Nexela/PickerExtended#61]
Was about to post this on the official forums before I realized the behavior only happened with Picker Extended enabled:

In Factorio 0.15.x, hitting R to to rotate transport belts being placed would only rotate those belts.  If the cursor happened to be over another transport belt at the same time, that belt would not be rotated.

In 0.16.1, "R" will rotate both the held item [i]and[/i] the entity the cursor is over.  Furthermore, the belt on the cursor will obscure the belt underneath it that is being rotated (possibly not in the same direction) to make it less noticeable that this is happening.  Previously, R only rotated placed entities if the hand was empty (or maybe if it held a non-rotatable item?)

**Comment by Nexela** [comment]
Noted.  Should be an easy fix to disable action when holding something in
hand.

**Comment by dewiniaid** [comment]
After confirming I'm using the latest version of PickerExtended and that my version actually includes e5db810c850c4be16514f71985934f03dded80bb, this issue still is very much present.

**Comment by Nexela** [comment]
Thanks for the follow up. Will address shortly
