### ISSUE TITLE
[Factorio 0.16.2][PE 3.0.0] Error when opening planner menu

### ISSUE THREAD

**Issue by mkaito** [Nexela/PickerExtended#63]
Opening the planner menu (default Shift B) yields the following non-fatal error:

 ```
503.688 Script @__PickerExtended__/stdlib/event/event.lua:160: LuaGuiElement doesn't contain key horizontal_scroll_policy.
stack traceback:
	__PickerExtended__/picker/planners.lua:32: in function 'get_or_create_planner_flow'
	__PickerExtended__/picker/planners.lua:77: in function <__PickerExtended__/picker/planners.lua:75>
	[C]: in function 'pcall'
	__PickerExtended__/stdlib/event/event.lua:155: in function <__PickerExtended__/stdlib/event/event.lua:134>

```

**Comment by Nexela** [comment]
Should be fixed in the latest release!
#62 
#8e9bddebd443f97f2a9b152fd51f73001c3e21e8

**Comment by mkaito** [comment]
You're a champ! Keep up the good work!

A friend in MP had an error that I can't seem to reproduce, something about "dolly_tick" when placing or rotating belts.

I'll ask him when he's back from class, but maybe that sounds familiar?

El 15 de diciembre de 2017 3:00:43 GMT+00:00, Nicholas Dunn <notifications@github.com> escribió:
>Should be fixed in the latest release!
>#62 
>#8e9bddebd443f97f2a9b152fd51f73001c3e21e8
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Nexela/PickerExtended/issues/63#issuecomment-351900239

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by Nexela** [comment]
That is fixed also

**Comment by mkaito** [comment]
Great stuff!

Thanks 😄
