### ISSUE TITLE
changelog.txt not actually included in release builds

### ISSUE THREAD

**Issue by dewiniaid** [Nexela/PickerExtended#68]
Out of all the Factorio mods, I figured yours would use the in-game changelog feature.  But the button was nowhere to be found.

I see the file on the repository and it looks to be in the correct format and old enough to have been around for a few releases .. so I unzipped the mod portal version of Picker Extended to take a look and it does not appear to be included in there.

Thought I'd give you a heads up.

**Comment by Nexela** [comment]
Uhoh!!  Thanks for the report.  I will update my release script to include
the changelog
