### ISSUE TITLE
Container with a filter that doesn't match the item in the slot causes exception in sortinventory.lua

### ISSUE THREAD

**Issue by dewiniaid** [Nexela/PickerExtended#69]
I had a cargo wagon full of various base supplies... and copied filters onto it from another cargo wagon.  This caused one of the slots to have an item in it that didn't match the filter.

Every time the the cargo wagon was opened (until I fixed the filtering issue):

`__PickerExtended__/picker/sortinventory.lua:222: bad argument #2 to '__index' (string expected, got nil)`

**Comment by Nexela** [comment]
Thanks for the report, I am waiting on an API request that will make sorting a lot better.
