### ISSUE TITLE
Mark empty drills not working correctly with Deep Core Mining.

### ISSUE THREAD

**Issue by CyaNox** [Nexela/PickerExtended#76]
In picker extended the option "Mark empty drills" marks deep core mining drills (which are on a infinite patch) for deconstruction when a normal miner in the neighborhood (not entirely sure what range this is) is depleted. https://mods.factorio.com/mod/vtk-deep-core-mining is the mod in question. I've not looked who is to blame for this yet :P

Here is an example image. The deep core mine was not near an ore. you can see where the closest "depleted" ore patch is near the bottom (also marked for deconstruction)

![](https://cdn.discordapp.com/attachments/306402592265732098/431091421651664907/20194433.png)

:fire: :fire: :fire:

**Comment by Nexela** [comment]
Do you have a save file I can test against?

**Comment by CyaNox** [comment]
Not a simple small one where you are next to the bug. The world from that image is many saves further so I don't have it in that state anymore. Maybe I'll bother with making one (it should be fairly simple to set something up where this is visible).
