### ISSUE TITLE
Craft selected entity even when have one

### ISSUE THREAD

**Issue by Dimava** [Nexela/PickerExtended#78]
Player should be able to craft selected entity with Alt-Q when he already have it in inventory.
It would also look great if, when using craft pipette, floating-text appeared showing number of pipetted items player will have after his crafting queue finishes.

**Comment by Dimava** [comment]
If the key for pick and craft pipettes is the same, feature may be either completely disabled, or enabled only when pipetting the same entity multiple times.

**Comment by Nexela** [comment]
Implemented I do believe
