### ISSUE TITLE
Chest Limiter limits are off by 1

### ISSUE THREAD

**Issue by Dimava** [Nexela/PickerExtended#79]
![image](https://user-images.githubusercontent.com/20068737/38776286-14966096-409d-11e8-9194-c3b4e06bf47b.png)
![image](https://user-images.githubusercontent.com/20068737/38776288-1d994c44-409d-11e8-8ba3-061d1c3519b4.png)

**Comment by Nexela** [comment]
I will look into this but it is sort of correct.  The bar stats at the 3rd
slot

**Comment by Dimava** [comment]
![image](https://github.com/Nexela/PickerExtended/raw/master/web/picker-chest-limit.gif)
Old gif shows it was. Probably some API changed

**Comment by Dimava** [comment]
Seems like not very stable
![image](https://cdn.discordapp.com/attachments/139677590393716737/435112383116214283/unknown.png)

**Comment by Nexela** [comment]
RuhRoh, what am I missing

**Comment by Nexela** [comment]
Trying to figure out what is going on.... Works correctly without picker-extended enabled.......

**Comment by Nexela** [comment]
Fixed the one issue,    As to the bar issue,   it seems to be working correct on my end (maybe I did fix it already)  Feel free to pull down again and play around (I am sure I broke more stuff)
