### ISSUE TITLE
Quick Blueprints

### ISSUE THREAD

**Issue by Dimava** [Nexela/PickerExtended#80]
~~- Add disposable blueprint to blueptint list (i.e. Pippete Blueprint which you may have only one at a time)~~

- Assimilate [Quickprint](https://mods.factorio.com/mod/er-quickprint)

**Comment by Nexela** [comment]
PS, it mostly is :)   just turn on blueprint eating in per player settings

**Comment by Dimava** [comment]
Quickprint does not needs confirmation. 
Original cleaning with Q (first cleans, second removes) would be also good.

**Comment by Nexela** [comment]
I will look into bypassing the confirmation screen (which can be done by holding down shift btw)
And a possible flag to just always zap pippette blueprints

**Comment by Dimava** [comment]
Didn't know about shift-select.
Shift-Q seems good for clearing then.

But tool made especially for copy-pasting is still a thing.

BTW, does Nanobots *not* rescanning ghosts immediately after blueprint/decon is set?
