### ISSUE TITLE
Always have empty blueprint in not-imported books

### ISSUE THREAD

**Issue by Dimava** [Nexela/PickerExtended#82]
Add empty blueprint to the end of each book you have in hands, so you can continue filling it.

Note: empty blueprints are ignored when saving to library.

Needs some inplementation ideas

**Comment by Nexela** [comment]
Implementation Idea,  Adjustment Pad + key adds an empty blueprint to the current book and sets the active index to it in hand, - removes any empty blueprints in the book starting at the end and setting active index to the last setup index.
