### ISSUE TITLE
Blueprint Books turn grey in Factorio 0.16.37

### ISSUE THREAD

**Issue by dewiniaid** [Nexela/PickerExtended#83]
Blueprint Books are now grey rather than blue if Picker Extended is enabled.  This did not happen prior to today's patch (0.16.37).

The config option to have colored blueprint books is disabled.

See https://i.imgur.com/g6gSAAc.png

**Comment by Nexela** [comment]
Are the colors correct if colored books are enabled?

**Comment by Nexela** [comment]
https://forums.factorio.com/viewtopic.php?t=59811
Fixed in the next version of Factorio
