### ISSUE TITLE
Reversing a belt duplicates/deletes items

### ISSUE THREAD

**Issue by jochemmeyers** [Nexela/PickerExtended#85]
Reversing a belt using the alt+R keycombo copies one side of the belt to the other. On a belt with only one side filled, this either clears the belt, or duplicates the contents as show in this gfy:

https://gfycat.com/DiscreteFilthyJaguarundi

This is on Factorio 0.16.38, PickerExtended version 3.0.3. For recording the demo, I disabled all other mods.

**Comment by jochemmeyers** [comment]
I've been seeing this bug since starting this playthrough on 0.16.36.

**Comment by Nexela** [comment]
Duplicate, fixes whenever I release
