### ISSUE TITLE
Vertical splitters are not mirrored

### ISSUE THREAD

**Issue by Dimava** [Nexela/PickerExtended#87]
![image](https://user-images.githubusercontent.com/20068737/39395360-6d9106bc-4ae6-11e8-853d-46468b2c9b44.png)
![image](https://user-images.githubusercontent.com/20068737/39395374-a0ba881a-4ae6-11e8-92ff-cbd7f99fd3a2.png)

**Comment by Nexela** [comment]
Is this from master or released version?

**Comment by Dimava** [comment]
Master

**Comment by Dimava** [comment]
Released is ok
