### ISSUE TITLE
Request: Screenshot camera with alt-info

### ISSUE THREAD

**Issue by StephanSteinert** [Nexela/PickerExtended#88]
Hi,

it would be nice, if i can make screenshots with the screenshot camera with alt-info enabled.

Cu, steinio.

**Comment by Dimava** [comment]
For Alt-mode use Shift-select

**Comment by Dimava** [comment]
I'd like 'extend to grid' option though. Precisely selecting pixels for corners is annoying.

**Comment by Nexela** [comment]
Hmmmm, I shall adjust the SC camera to expand to the tile grid. Will that work?
