### ISSUE TITLE
[Hacky] Replacement Blueprint

### ISSUE THREAD

**Issue by Dimava** [Nexela/PickerExtended#89]
In 0.15 there was an [Cut and paste tools](https://mods.factorio.com/mod/cut-and-paste) mod that by some really weird hacky methods allowed user to take a 'cut' blueprint and place it on actually same place (a couple if tiles off), _ignoring build_ 'cutted' structures that were removed after blueprint placement.

On base of that mod it is probably possible to implement 'impossible' Replacement Blueprint, than is wanted but was never implemented.

Edit: found [0.16 fix](https://mods.factorio.com/mod/cut-and-paste-016)  ([Github](https://github.com/mickael9/cut-and-paste))

**Comment by Nexela** [comment]
Closed as .17 will obsolete. (mostly)
