### ISSUE TITLE
Broken startup settings usage

### ISSUE THREAD

**Issue by Rseding91** [Nexela/PickerExtended#91]
https://github.com/Nexela/PickerExtended/blob/master/prototypes/notes.lua#L4 conditionally requires files using startup settings which is invalid and causes errors like this when used in multiplayer: https://media.discordapp.net/attachments/458687692855836722/476122968255365161/New_Bitmap_Image.jpg?width=897&height=468

Specifically: **Do not conditionally 'require(...)' things: this breaks the crc checks and people will get errors trying to use your mod in multiplayer. 'require(...)' everything and then conditionally add the values to data.raw using the settings.**

**Comment by Nexela** [comment]
Fixed my oopsie, Script was supposed to return after the requires since everything below it is just conditional extending.
